In [2]:
import pandas as pd
import numpy as np
# Sample dataset
data = {'Name': ['Alice', 'Bob', 'Charlie', 'Alice', 'Eve', 'Frank', 'Grace', 'Heidi'],'Age': [25, 30, 35, 25, 29, 45, 50, 22],'Score': [88, 90, 85, 88, 76, 95, 67, 70],'Gender': ['F', 'M', 'M', 'F', 'F', 'M', 'F', 'F']
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)
# 1. Removing Duplicates
df = df.drop_duplicates()
print("\nAfter Removing Duplicates:")
print(df)
# 2. Adding a Column
df['Pass'] = df['Score'] >= 75
print("\nAfter Adding 'Pass' Column:")
print(df)
# 3. Replacing Values
df['Gender'] = df['Gender'].replace({'F': 'Female', 'M': 'Male'})
print("\nAfter Replacing Gender Values:")
print(df)
# 4. Renaming Axis / Index
df.rename(index={0: 'ID001', 1: 'ID002'}, inplace=True)
print("\nAfter Renaming Index:")
print(df)
# 5. Discretization / Binning Age
df['Age_Group'] = pd.cut(df['Age'], bins=[0, 25, 35, 50], labels=['Young', 'Middle-aged', 'Senior'])
print("\nAfter Binning 'Age' into Age_Group:")
print(df)
# 6. Detecting and Filtering Outliers in Score (IQR Method)
Q1 = df['Score'].quantile(0.25)
Q3 = df['Score'].quantile(0.75)
IQR = Q3 - Q1
filtered_df = df[(df['Score'] >= Q1 - 1.5 * IQR) & (df['Score'] <= Q3 + 1.5 * IQR)]
print("\nAfter Filtering Outliers in 'Score':")
print(filtered_df)
# 7. Permutation and Random Sampling
N
sample_df = df.sample(n=3, random_state=1)
print("\nShuffled DataFrame:")
print(shuffled_df)
print("\nRandom Sample of 3 Rows:")
print(sample_df)
# 8. Computing Indicator/Dummy Variables
df_with_dummies = pd.get_dummies(df, columns=['Gender'])
print("\nAfter Computing Dummy Variables for 'Gender':")
print(df_with_dummies)

Original DataFrame:
      Name  Age  Score Gender
0    Alice   25     88      F
1      Bob   30     90      M
2  Charlie   35     85      M
3    Alice   25     88      F
4      Eve   29     76      F
5    Frank   45     95      M
6    Grace   50     67      F
7    Heidi   22     70      F

After Removing Duplicates:
      Name  Age  Score Gender
0    Alice   25     88      F
1      Bob   30     90      M
2  Charlie   35     85      M
4      Eve   29     76      F
5    Frank   45     95      M
6    Grace   50     67      F
7    Heidi   22     70      F

After Adding 'Pass' Column:
      Name  Age  Score Gender   Pass
0    Alice   25     88      F   True
1      Bob   30     90      M   True
2  Charlie   35     85      M   True
4      Eve   29     76      F   True
5    Frank   45     95      M   True
6    Grace   50     67      F  False
7    Heidi   22     70      F  False

After Replacing Gender Values:
      Name  Age  Score  Gender   Pass
0    Alice   25     88  Female   True
1      Bob   30     90    Male   True
2  Charlie   35     85    Male   True
4      Eve   29     76  Female   True
5    Frank   45     95    Male   True
6    Grace   50     67  Female  False
7    Heidi   22     70  Female  False

After Renaming Index:
          Name  Age  Score  Gender   Pass
ID001    Alice   25     88  Female   True
ID002      Bob   30     90    Male   True
2      Charlie   35     85    Male   True
4          Eve   29     76  Female   True
5        Frank   45     95    Male   True
6        Grace   50     67  Female  False
7        Heidi   22     70  Female  False

After Binning 'Age' into Age_Group:
          Name  Age  Score  Gender   Pass    Age_Group
ID001    Alice   25     88  Female   True        Young
ID002      Bob   30     90    Male   True  Middle-aged
2      Charlie   35     85    Male   True  Middle-aged
4          Eve   29     76  Female   True  Middle-aged
5        Frank   45     95    Male   True       Senior
6        Grace   50     67  Female  False       Senior
7        Heidi   22     70  Female  False        Young

After Filtering Outliers in 'Score':
          Name  Age  Score  Gender   Pass    Age_Group
ID001    Alice   25     88  Female   True        Young
ID002      Bob   30     90    Male   True  Middle-aged
2      Charlie   35     85    Male   True  Middle-aged
4          Eve   29     76  Female   True  Middle-aged
5        Frank   45     95    Male   True       Senior
6        Grace   50     67  Female  False       Senior
7        Heidi   22     70  Female  False        Young

NameError: name 'N' is not defined