In [ ]:
#18.DATA CLEANING
import numpy as np
import pandas as pd
data={"Name":['Alice','Bob','Charlie','David','Eve'],'Age':[25,np.nan,35,40,28],'Salary':[50000,60000,np.nan,70000,62000],'Allowances':[2000,np.nan,2000,2000,2500]}
df=pd.DataFrame(data)
print("Actual data frame:\n",df)
print("missing values:\n",df.isnull())
print("Dropping missing values:\n",df.dropna())
print("replacing missing values with zeros:\n",df.fillna(0))